nome = input("Digite seu nome:")
print(f"{nome}")
rg = input('Digite seu rg;')
print(f'{rg}')
cpf = input('Digite seu cpf:')
print(f'{cpf}')
telefone = input('Digite seu telefone:')
print(f'{telefone}')
ender = input('Digite seu endereço:')
print(f'{ender}')
cep = input('Digite seu cep:')
print(f'{cep}')
sexo = input('Digite seu sexo:')
print(f'{sexo}')
